services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw123456
    ports:
      - "5432:5432"
    restart: unless-stopped
